services:
  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z
    command: ["server", "--console-address", ":9001", "${ROOT_DATA}"]
    ports:
      - "${API_PORT}:9000"
      - "${CONSOLE_PORT}:9001"
    environment:
      - MINIO_ROOT_USER=${ROOT_USER}
      - MINIO_ROOT_PASSWORD=${ROOT_PASSWORD}
      - MINIO_IDENTITY_OPENID_CONFIG_URL_PRIMARY_IAM=${OPENID_CONFIG_URL}
      - MINIO_IDENTITY_OPENID_CLIENT_ID_PRIMARY_IAM=${OPENID_CLIENT_ID}
      - MINIO_IDENTITY_OPENID_CLIENT_SECRET_PRIMARY_IAM=${OPENID_CLIENT_SECRET}
      - MINIO_IDENTITY_OPENID_DISPLAY_NAME_PRIMARY_IAM=${OPENID_DISPLAY_NAME}
      - MINIO_IDENTITY_OPENID_SCOPES_PRIMARY_IAM=${OPENID_SCOPES}
      - MINIO_IDENTITY_OPENID_REDIRECT_URI=${OPENID_REDIRECT_URI}
    volumes:
      - minio:${ROOT_DATA}
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  minio:
    external: false
