services:
  minio:
    image: quay.io/minio/aistor/minio:latest
    pull_policy: always
    command: server /mnt/data --console-address ":9001" --license /minio.license
    ports:
      - "${S3_PORT}:9000"
      - "${ADMIN_PORT}:9001"
    environment:
      MINIO_ROOT_USER: ${ROOT_USER}
      MINIO_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}:/mnt/data
      - ${LICENSE_PATH}:/minio.license:ro
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
